path_to_jobs: './applications/ansible/ansible-jenkins/files/jobs/'
path_to_dsl: './applications/ansible/ansible-jenkins/files/jobs/scripts/dsl.groovy'
debugging: True
repositories:
  jenkins_config: 'https://github.com/jaycarson/Portfolio.git'
  code: 'https://github.com/jaycarson/fun.git'
job_replacements:
  stand_in: 'Something'
