Global:
  debugging: 3
  path_to_dsl: './applications/ansible/ansible-jenkins/files/scripts/dsl.groovy'
  path_jenkins: '/var/lib/jenkins'
repositories:
  Portfolio:
    location: 'https://github.com/jaycarson/Portfolio.git'
    jobs:
      - location: './applications/ansible/ansible-jenkins/files/jobs/test_python_2_7.groovy'
        branches:
          - 'master'
        variables:
          PATH: 'scripting_languages/Python_2_7/Eulers'
    pipelines:
      - pipelinefile: './applications/ansible/ansible-jenkins/files/pipelines/example/config.xml'
        jenkinsfile: './applications/ansible/ansible-jenkins/files/pipelines/example/Jenkinsfile'
        name: 'test-pipeline'
        branches:
          - 'master'
  fun:
    location: 'https://github.com/jaycarson/fun.git'
    jobs:
      - location: 'app/rsc/CI/jobs/test.job'
        branches:
          - 'master'
          - '^DEV'  # REGEX
    jobs:
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'base'
          SOURCE_MAP_TYPE: 'noise'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenBase.py'
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'feature'
          SOURCE_MAP_TYPE: 'base'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenFeature.py'
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'feature'
          SOURCE_MAP_TYPE: 'terrain'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenTerrain.py'
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'terrain'
          SOURCE_MAP_TYPE: 'castle'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenCastle.py'
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'castle'
          SOURCE_MAP_TYPE: 'farm'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenFarms.py'
      - location: 'app/rsc/CI/jobs/generate_maps.groovy'
        branches:
          - 'master'
          - '^DEV'  # REGEX
        variables:
          ARTIFACT_REPO_PATH: '/tmp/artifact_repo/game_maps/'
          MAP_TYPE: 'farm'
          SOURCE_MAP_TYPE: 'house'
          PATH: 'app/rsc/MapGeneration'
          SCRIPT: 'MapGenHouse.py'
    jenkins_config_jobs:
      - location: ''
        branches:
          - 'master'
variables:
  SOMETHING: 'Something Else'
