Global:
  debugging: 1
  path_to_dsl: './applications/ansible/ansible-jenkins/files/scripts/dsl.groovy'
  path_jenkins: '/var/lib/jenkins/'
repositories:
  jenkins_config:
    location: 'https://github.com/jaycarson/Portfolio.git'
    jobs:
      - location: './applications/ansible/ansible-jenkins/files/jobs/test_python_2_7.groovy'
        branches:
          - 'master'
        replacements:
          - Description: 'Root Path'
            replace: '{{PATH}}'
            with: 'scripting_languages/Python_2_7/Eulers'
    pipelines:
      - pipelinefile: './applications/ansible/ansible-jenkins/files/pipelines/example/config.xml'
        jenkinsfile: './applications/ansible/ansible-jenkins/files/pipelines/example/Jenkinsfile'
        name: 'test-pipeline'
        branches:
          - 'master'
  code:
    location: 'https://github.com/jaycarson/fun.git'
    jobs:
      - location: ''
        branches:
        - 'master'
        - '^DEV'  # REGEX
    jenkins_config_jobs:
      - location: ''
        branches:
        - 'master'
job_replacements:
  - Description:
    replace: '{{Something}}'
    with: 'Something Else'
