Global:
  debugging: 1
  path_to_dsl: './applications/ansible/ansible-jenkins/files/scripts/dsl.groovy'
repositories:
  jenkins_config:
    location: 'https://github.com/jaycarson/Portfolio.git'
    jobs:
      - location: './applications/ansible/ansible-jenkins/files/jobs/test_python_2_7.groovy'
        branches:
          - 'master'
        replacements:
          - Root_Path:
            replace: '{{PATH}}'
            with: 'scripting_languages/Python_2_7/Eulers'
    pipelines:
      - location: './applications/ansible/ansible-jenkins/files/pipelines/example/Jenkinsfile'
        branches:
          - 'master'
  code:
    location: 'https://github.com/jaycarson/fun.git'
    jobs:
      - location: ''
        branches:
        - 'master'
        - '^DEV'  # REGEX
    jenkins_config_jobs:
      - location: ''
        branches:
        - 'master'
job_replacements:
  - Description:
    - replace: '{{Something}}'
    - with: 'Something Else'
