---
# defaults file for ansible-jenkins


# ============================== #
# Version Information            #
# ============================== #
jenkins_version: "2.121.1" # The exact version of jenkins to deploy
jenkins_java_version: "java-1.8.0-openjdk-amd64"


# ============================== #
# Environment Variables          #
# ============================== #
# jenkins_url:  The IP Address of the Jenkins Server
# jenkins_port: The port that Jenkins will listen on
# jenkins_home: The directory on the server where the Jenkins configs will live
# jenkins_admin The admininstrator email address for the Jenkins server
jenkins_url: "http://127.0.0.1"
jenkins_port: "8080"
jenkins_home: /var/lib/jenkins
jenkins_admin: "admin@example.com"


# ============================== #
# Jenkins installation overrides #
# ============================== #
jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"


# ============================ #
# Configuration File Ownership #
# ============================ #
jenkins_config_owner: "jenkins"
jenkins_config_group: "jenkins"


# ============================ #
# Configuration File Locations #
# ============================ #
jenkins_source_dir_configs: "{{ playbook_dir }}/jenkins-configs"
jenkins_source_dir_jobs: "{{ jenkins_source_dir_configs }}/jobs"


# ============================ #
# config.xml template source   #
# ============================ #
jenkins_source_config_xml: "{{ jenkins_source_dir_configs }}/config.xml"


# ============================================= #
# Include custom files for jenkins installation #
# ============================================= #
jenkins_include_custom_files: false
jenkins_custom_files: {} # src and dest names


# ============================================= #
# Include secrets directory during installation #
# ============================================= #
jenkins_include_secrets: false
jenkins_source_secrets: "{{ jenkins_source_dir_configs }}/secrets/"


# ================================== #
# The names of the jobs              #
# (config.xml must exist under       #
# jenkins_source_dir_jobs/job_name/) #
# ================================== #
jenkins_jobs:
  - seed_job


# ============================ #
# Plugins to be installed      #
# ============================ #
jenkins_plugins:
  - git
  - log-parser
  - copyartifact
  - workflow-aggregator
  - workflow-multibranch
  - docker-workflow
  - template-project
  - ec2
  - job-dsl
  - cobertura


# ============================== #
# Custom Plugins to be installed #
# ============================== #
jenkins_custom_plugins: []
