---

- name: jenkins-start => Start Jenkins
  become: true
  service:
    name: jenkins
    state: started

- name: jenkins-start => Wait for Jenkins to start
  uri:
    url: "{{ jenkins_url }}:{{ jenkins_port }}"
  become: false
  register: jenkins_home_content
  # Jenkins will return 503 
  # (service unavailable) on the home 
  # page while starting the "please 
  # wait while Jenkins is getting 
  # ready to work" page.
  until: jenkins_home_content.status == 200
  retries: 150
  delay: 1
