---
- name: Install Java 8
  dnf:
    name: "{{ jenkins_java_version }}"
    state: latest
    become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"
