#!/usr/bin/perl

package Euler002;

use strict;
use warnings;

use Getopt::Long qw(GetOptions);

=head1 NAME

Euler002 - This script is to solve the following Euler Problem:

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.

=head1 SYNOPSYS

Euler002.pm [OPTION]... [PARAMETER]...

=head1 Description

This template is used to get a head start when writing a script.

=head1 OPTIONS

=over 12

=item C<restrict>

This is a numeric parameter used to restrict the calculation. Usage: "perl perl_template.pm restrict=10"

=back

=head1 License

=over 12

Copyright 2018 James Carson

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

=back

=cut

sub new{
    my ( $class, %args ) = @_;

    my $self = {
        _restrict => $args{restrict} || 4000000,
        };
    bless $self, $class;
}

sub set_restrict{ my Euler002 $self=$_[0]; $self->{_restrict}=$_[1];  }

sub get_restrict{ my Euler002 $self=$_[0]; return $self->{_restrict}; }

sub init{
    my Euler002 $self = shift;
}

sub run{
    my Euler002 $self = shift;
    my $value_this    = 1;
    my $value_next    = 2;
    my $value_last    = 0;
    my $answer = 0;

    while ( $value_this < $self->get_restrict() ){
        if( $value_this % 2 == 0 ){
            $answer = $answer + $value_this;
        }
        $value_next = $self->next_fib_number( $value_this, $value_last );
        $value_last = $value_this;
        $value_this = $value_next;
    }
    return $answer;
}

sub next_fib_number{
    my Euler002 $self = $_[0];
    my $value_this    = $_[1];
    my $value_last    = $_[2];
    return ( $value_this + $value_last );
}


unless ( caller ){
    my $restrict = '';

    my $options = GetOptions(
        'restrict=i' => \$restrict,
    ) or die "Euler002.pm: Invalid options passed: $0\n";

    my $app = Euler002->new(
        restrict => $restrict,
    );
    
    $app->init();
    $app->run();
}

1;
